[0m18:35:07.724359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aa9550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108937c50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108937b10>]}


============================== 18:35:07.750733 | 05ed0f2e-e573-4ddb-9c2e-7664f8c52910 ==============================
[0m18:35:07.750733 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:35:07.752494 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mariasamper/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:35:07.820914 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/mariasamper/.dbt')}
[0m18:35:07.821823 [info ] [MainThread]: Creating dbt configuration folder at 
[0m18:35:19.884009 [debug] [MainThread]: Starter project path: /Users/mariasamper/Documents/de-zoomcamp-2025/week_4/dbt_taxi_rides/venv/lib/python3.13/site-packages/dbt/include/starter_project
[0m18:35:19.912847 [info ] [MainThread]: 
Your new dbt project "dbt_taxi_ny" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:35:19.913539 [info ] [MainThread]: Setting up your profile.
[0m18:38:48.965503 [info ] [MainThread]: Profile dbt_taxi_ny written to /Users/mariasamper/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:38:48.987254 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 221.42648, "process_in_blocks": "0", "process_kernel_time": 1.07557, "process_mem_max_rss": "169578496", "process_out_blocks": "0", "process_user_time": 4.373999}
[0m18:38:48.989418 [debug] [MainThread]: Command `dbt init` succeeded at 18:38:48.988949 after 221.43 seconds
[0m18:38:48.992451 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11fc31220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108831a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11fbf27a0>]}
[0m18:38:48.996369 [debug] [MainThread]: Flushing usage events
[0m18:38:49.697398 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:38:59.325759 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10fe3d550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110ccf9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110ccfc50>]}


============================== 18:38:59.349019 | 20c800ec-0358-47ec-9e74-ff00a997405c ==============================
[0m18:38:59.349019 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:38:59.350851 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/mariasamper/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m18:38:59.426192 [info ] [MainThread]: dbt version: 1.9.2
[0m18:38:59.427148 [info ] [MainThread]: python version: 3.13.1
[0m18:38:59.427764 [info ] [MainThread]: python path: /Users/mariasamper/Documents/de-zoomcamp-2025/week_4/dbt_taxi_rides/venv/bin/python3.13
[0m18:38:59.428631 [info ] [MainThread]: os info: macOS-13.7.2-x86_64-i386-64bit-Mach-O
[0m18:39:02.751646 [info ] [MainThread]: Using profiles dir at /Users/mariasamper/.dbt
[0m18:39:02.752408 [info ] [MainThread]: Using profiles.yml file at /Users/mariasamper/.dbt/profiles.yml
[0m18:39:02.753015 [info ] [MainThread]: Using dbt_project.yml file at /Users/mariasamper/Documents/de-zoomcamp-2025/week_4/dbt_taxi_rides/dbt_project.yml
[0m18:39:02.753643 [info ] [MainThread]: adapter type: bigquery
[0m18:39:02.754415 [info ] [MainThread]: adapter version: 1.9.1
[0m18:39:02.755252 [info ] [MainThread]: Configuration:
[0m18:39:02.756065 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m18:39:02.756742 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:39:02.758155 [info ] [MainThread]: Required dependencies:
[0m18:39:02.758891 [debug] [MainThread]: Executing "git --help"
[0m18:39:02.807071 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:39:02.808775 [debug] [MainThread]: STDERR: "b''"
[0m18:39:02.809403 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:39:02.810445 [info ] [MainThread]: Connection:
[0m18:39:02.811482 [info ] [MainThread]:   method: oauth
[0m18:39:02.812412 [info ] [MainThread]:   database: de-zoomcamp-451410
[0m18:39:02.813487 [info ] [MainThread]:   execution_project: de-zoomcamp-451410
[0m18:39:02.814914 [info ] [MainThread]:   schema: dbt_taxi
[0m18:39:02.816160 [info ] [MainThread]:   location: US
[0m18:39:02.817177 [info ] [MainThread]:   priority: interactive
[0m18:39:02.818082 [info ] [MainThread]:   maximum_bytes_billed: None
[0m18:39:02.818640 [info ] [MainThread]:   impersonate_service_account: None
[0m18:39:02.819158 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m18:39:02.819735 [info ] [MainThread]:   job_retries: 1
[0m18:39:02.820270 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m18:39:02.820797 [info ] [MainThread]:   job_execution_timeout_seconds: 300
[0m18:39:02.821306 [info ] [MainThread]:   timeout_seconds: 300
[0m18:39:02.821792 [info ] [MainThread]:   client_id: None
[0m18:39:02.823624 [info ] [MainThread]:   token_uri: None
[0m18:39:02.824172 [info ] [MainThread]:   dataproc_region: None
[0m18:39:02.824698 [info ] [MainThread]:   dataproc_cluster_name: None
[0m18:39:02.825385 [info ] [MainThread]:   gcs_bucket: None
[0m18:39:02.826126 [info ] [MainThread]:   dataproc_batch: None
[0m18:39:02.827538 [info ] [MainThread]: Registered adapter: bigquery=1.9.1
[0m18:39:03.271589 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m18:39:03.272684 [debug] [MainThread]: On debug: select 1 as id
[0m18:39:03.273362 [debug] [MainThread]: Opening a new connection, currently in state init
[0m18:39:06.174888 [debug] [MainThread]: BigQuery adapter: Got an error when attempting to create a bigquery " "client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m18:39:06.176343 [debug] [MainThread]: BigQuery adapter: Unhandled error while running:
select 1 as id
[0m18:39:06.177365 [debug] [MainThread]: BigQuery adapter: Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m18:39:06.178463 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m18:39:06.185661 [info ] [MainThread]: [31m2 checks failed:[0m
[0m18:39:06.187000 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/mariasamper/Documents/de-zoomcamp-2025/week_4/dbt_taxi_rides/dbt_project.yml> not found

[0m18:39:06.187810 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >'NoneType' object has no attribute 'close'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m18:39:06.195114 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 6.9872527, "process_in_blocks": "0", "process_kernel_time": 1.234531, "process_mem_max_rss": "177520640", "process_out_blocks": "0", "process_user_time": 4.513208}
[0m18:39:06.195957 [debug] [MainThread]: Command `dbt debug` failed at 18:39:06.195766 after 6.99 seconds
[0m18:39:06.196677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128052780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128089a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x127f6bbd0>]}
[0m18:39:06.197369 [debug] [MainThread]: Flushing usage events
[0m18:39:06.893600 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:40:50.720350 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10f769550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1106079d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110607c50>]}


============================== 20:40:50.744637 | 1c5e5129-a07c-4714-b346-982f02c6a1d0 ==============================
[0m20:40:50.744637 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:40:50.746296 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/mariasamper/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt build -s fct_taxi_trips_monthly_fare_p95', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:40:50.747407 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mariasamper/Documents/de-zoomcamp-2025/week_4/dbt_taxi_rides/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:40:50.753347 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.16398199, "process_in_blocks": "0", "process_kernel_time": 0.745955, "process_mem_max_rss": "89415680", "process_out_blocks": "0", "process_user_time": 2.455961}
[0m20:40:50.754733 [debug] [MainThread]: Command `dbt build` failed at 20:40:50.754134 after 0.17 seconds
[0m20:40:50.755412 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110628d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1104f31d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11046b240>]}
[0m20:40:50.755964 [debug] [MainThread]: Flushing usage events
[0m20:40:51.231071 [debug] [MainThread]: An error was encountered while trying to flush usage events
